import { Almacen } from './almacen.model';
import { Categoria } from './categoria.model';

export class Insumo {
  constructor(
    public readonly id: number,
    public readonly nombre: string,
    public readonly descripcion?: string,
    public readonly fotoUrl?: string,
    public readonly presentacionTipo?: string,
    public readonly presentacionCantidad?: number,
    public readonly presentacionUnidad?: string,
    public readonly unidadUso?: string,
    public readonly tipoMateria?: string,
    public readonly factorConversionUso?: number,
    public readonly stockPresentacion?: number,
    public readonly stockUso?: number,
    public readonly precioUnitarioPresentacion?: number,
    public readonly precioUnitarioUso?: number,
    public readonly valorInventario?: number,
    public readonly almacenId?: number,
    public readonly proveedorId?: number,
    public readonly categoriaId?: number,
    public readonly fechaRegistro?: Date,
    public readonly creadoPorUsuarioId?: number,
    public readonly tipoInsumo?: string,
    public readonly costoAdquisicion?: number,
    public readonly valorResidual?: number,
    public readonly vidaUtilHoras?: number,
    public readonly horasUsadas?: number,
    public readonly stockReservado?: number,
    public readonly depreciacionAcumulada?: number,
    public readonly stockMinimo?: number,
    public readonly estado?: string,
    public readonly costoUnitario?: number,
    public readonly fechaAdquisicion?: Date,
    public readonly fechaUltimoMantenimiento?: Date,
    public readonly fechaBaja?: Date,
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
    public readonly deletedAt?: Date,
    public readonly almacen?: Almacen,
    public readonly categoria?: Categoria,
  ) {}
}
